/**
 * BarGroup automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ResourceAbstract} from "sdkgen-client"
import BarByFooResource from "./BarByFooResource";
import BarByYearResource from "./BarByYearResource";

export default class BarGroup extends ResourceAbstract {
    /**
     * Endpoint: /bar/:foo
     */
    public getBarByFoo(foo: string): BarByFooResource
    {
        return new BarByFooResource(
            foo,
            this.baseUrl,
            this.httpClient
        );
    }

    /**
     * Endpoint: /bar/$year<[0-9]+>
     */
    public getBarByYear(year: string): BarByYearResource
    {
        return new BarByYearResource(
            year,
            this.baseUrl,
            this.httpClient
        );
    }

}
