/**
 * BazTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {AxiosInstance, AxiosRequestConfig, AxiosResponse} from "axios";
import {TagAbstract} from "sdkgen-client"

export default class BazTag extends TagAbstract {
    /**
     * Returns a collection
     *
     * @returns {Promise<EntryCollection>}
     * @throws {ErrorException}
     */
    public async get(year: string): Promise<EntryCollection> {
        const url = this.parser.url('/bar/$year&lt;[0-9]+&gt;', {
            year: year,
        });

        let params: AxiosRequestConfig = {
            url: url,
            method: 'GET',
            params: this.parser.query({
            }),
        };

        try {
            const response = await this.httpClient.request<EntryCollection>(params);
            return response.data;
        } catch (error) {
            if (axios.isAxiosError(error) && error.response) {
                switch (error.response.status) {
                    default:
                        throw new ErrorException('The server returned an unknown status code');
                }
            }

            throw new ErrorException('An unknown error occurred: ' + String(error));
        }
    }

    /**
     * @returns {Promise<EntryMessage>}
     * @throws {ErrorException}
     */
    public async create(payload: EntryCreate): Promise<EntryMessage> {
        const url = this.parser.url('/bar/$year&lt;[0-9]+&gt;', {
        });

        let params: AxiosRequestConfig = {
            url: url,
            method: 'POST',
            params: this.parser.query({
            }),
            data: payload
        };

        try {
            const response = await this.httpClient.request<EntryMessage>(params);
            return response.data;
        } catch (error) {
            if (axios.isAxiosError(error) && error.response) {
                switch (error.response.status) {
                    default:
                        throw new ErrorException('The server returned an unknown status code');
                }
            }

            throw new ErrorException('An unknown error occurred: ' + String(error));
        }
    }


}
