/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ClientAbstract, CredentialsInterface, TokenStoreInterface} from "sdkgen-client"
import {HttpBearer} from "sdkgen-client"


export default class Client extends ClientAbstract {
    public constructor(baseUrl: string, token: string, tokenStore: TokenStoreInterface|null = null, scopes: Array<string>|null = []) {
        super(baseUrl, new HttpBearer(token), tokenStore, scopes);
    }

    public foo(): FooTag
    {
        return new FooTag(
            this.httpClient,
            this.parser
        );
    }

    public bar(): BarTag
    {
        return new BarTag(
            this.httpClient,
            this.parser
        );
    }

    public baz(): BazTag
    {
        return new BazTag(
            this.httpClient,
            this.parser
        );
    }




}
