/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ClientAbstract, CredentialsInterface, TokenStoreInterface, HttpRequest} from "sdkgen-client"
import {HttpBearer} from "sdkgen-client"
import {Anonymous} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {FooTag} from "./FooTag";
import {BarTag} from "./BarTag";

export class Client extends ClientAbstract {
    public foo(): FooTag
    {
        return new FooTag(
            this.httpClient,
            this.parser
        );
    }

    public bar(): BarTag
    {
        return new BarTag(
            this.httpClient,
            this.parser
        );
    }



    public static build(token: string): Client
    {
        return new Client('http://api.foo.com', new HttpBearer(token));
    }

    public static buildAnonymous(): Client
    {
        return new Client('http://api.foo.com', new Anonymous());
    }
}
