/**
 * EntryCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {Entry} from "./Entry";

export interface EntryCollection {
    entry?: Array<Entry>
}

