/**
 * FooTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {AxiosInstance, AxiosRequestConfig, AxiosResponse} from "axios";
import {TagAbstract} from "sdkgen-client"

export default class FooTag extends TagAbstract {
    /**
     * Returns a collection
     *
     * @returns {Promise<AxiosResponse<EntryCollection>>}
     */
    public async get(): Promise<AxiosResponse<EntryCollection>> {
        const url = this.parser.url('/foo', {
        });

        let params: AxiosRequestConfig = {
            url: url,
            method: 'GET',
            params: this.parser.query({
            }),
        };

        return this.httpClient.request<EntryCollection>(params);
    }

    /**
     * @returns {Promise<AxiosResponse<EntryMessage>>}
     */
    public async create(payload: EntryCreate): Promise<AxiosResponse<EntryMessage>> {
        const url = this.parser.url('/foo', {
        });

        let params: AxiosRequestConfig = {
            url: url,
            method: 'POST',
            params: this.parser.query({
            }),
            data: payload
        };

        return this.httpClient.request<EntryMessage>(params);
    }


}
