/**
 * FooTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import axios, {AxiosRequestConfig} from "axios";
import {TagAbstract} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {FooBarTag} from "./FooBarTag";
import {FooBazTag} from "./FooBazTag";

export class FooTag extends TagAbstract {
    public bar(): FooBarTag
    {
        return new FooBarTag(
            this.httpClient,
            this.parser
        );
    }

    public baz(): FooBazTag
    {
        return new FooBazTag(
            this.httpClient,
            this.parser
        );
    }


}
