
// BarGroup automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    "encoding/json"
    "io/ioutil"
    "net/http"
    "time"
    "github.com/apioo/sdkgen-go"
)

type BarGroup struct {
    resource *sdkgen.Resource
}

// getBarByFoo Endpoint: /bar/:foo
func (group BarGroup) getBarByFoo(foo string) *BarByFooResource {
    return NewBarByFooResource(foo, group.resource)
}

// getBarByYear Endpoint: /bar/$year<[0-9]+>
func (group BarGroup) getBarByYear(year string) *BarByYearResource {
    return NewBarByYearResource(year, group.resource)
}


func NewBarGroup(resource *sdkgen.Resource) *BarGroup {
    return &BarGroup {
        resource: resource,
    }
}
