
// BarGroup automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    "github.com/apioo/sdkgen-go"
)

type BarGroup struct {
    resource *sdkgen.Resource
}

// GetBarByFoo Endpoint: /bar/:foo
func (group BarGroup) GetBarByFoo(foo string) *BarByFooResource {
    return NewBarByFooResource(foo, group.resource)
}

// GetBarByYear Endpoint: /bar/$year<[0-9]+>
func (group BarGroup) GetBarByYear(year string) *BarByYearResource {
    return NewBarByYearResource(year, group.resource)
}


func NewBarGroup(resource *sdkgen.Resource) *BarGroup {
    return &BarGroup {
        resource: resource,
    }
}
