
// Client automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    "github.com/apioo/sdkgen-go"
)

type Client struct {
    internal *sdkgen.Client
}

func (client *Client) Foo() *FooTag {
    return New(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Bar() *BarTag {
    return New(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Baz() *BazTag {
    return New(client.internal.HttpClient, client.internal.Parser)
}





func Build(token string) *Client {
    var credentials := sdkgen.HttpBearer{Token: token}

    return &Client {
        internal: sdkgen.NewClient(baseUrl, credentials, tokenStore, scopes),
    }
}
