
// Client automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    "github.com/apioo/sdkgen-go"
)

type Client struct {
    internal *sdkgen.Client
}

func (client *Client) Foo() *FooTag {
    return New(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Bar() *BarTag {
    return New(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Baz() *BazTag {
    return New(client.internal.HttpClient, client.internal.Parser)
}





func Build(token string) (*Client, error) {
    var credentials = sdkgen.HttpBearer{Token: token}

    client, err := sdkgen.NewClient("http://api.foo.com", credentials)
    if err != nil {
        return &Client{}, err
    }

    return &Client {
        internal: client,
    }, nil
}
