
// FooGroup automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    "encoding/json"
    "io/ioutil"
    "net/http"
    "time"
    "github.com/apioo/sdkgen-go"
)

type FooGroup struct {
    resource *sdkgen.Resource
}

// getFoo Endpoint: /foo
func (group FooGroup) getFoo() *FooResource {
    return NewFooResource(group.resource)
}


func NewFooGroup(resource *sdkgen.Resource) *FooGroup {
    return &FooGroup {
        resource: resource,
    }
}
