
// FooGroup automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    "github.com/apioo/sdkgen-go"
)

type FooGroup struct {
    resource *sdkgen.Resource
}

// GetFoo Endpoint: /foo
func (group FooGroup) GetFoo() *FooResource {
    return NewFooResource(group.resource)
}


func NewFooGroup(resource *sdkgen.Resource) *FooGroup {
    return &FooGroup {
        resource: resource,
    }
}
