
// entry_message automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type EntryMessage struct {
    Success bool `json:"success"`
    Message string `json:"message"`
}
