
// get_query automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


import "time"
type GetQuery struct {
    StartIndex int `json:"startIndex"`
    Float float64 `json:"float"`
    Boolean bool `json:"boolean"`
    Date time.Time `json:"date"`
    Datetime time.Time `json:"datetime"`
}
