<?php
/**
 * Path automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Foo\Bar;

use PSX\Schema\Attribute\Required;

#[Required(array('name', 'type'))]
class Path implements \JsonSerializable
{
    protected ?string $name = null;
    protected ?string $type = null;
    public function setName(?string $name) : void
    {
        $this->name = $name;
    }
    public function getName() : ?string
    {
        return $this->name;
    }
    public function setType(?string $type) : void
    {
        $this->type = $type;
    }
    public function getType() : ?string
    {
        return $this->type;
    }
    public function jsonSerialize() : object
    {
        return (object) array_filter(array('name' => $this->name, 'type' => $this->type), static function ($value) : bool {
            return $value !== null;
        });
    }
}
