/**
 * app automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import { Controller, Get, Post, Put, Patch, Delete, HttpCode, Param, Query, Headers, Body } from '@nestjs/common'
import { Entry } from "../dto/Entry";
import { EntryCollection } from "../dto/EntryCollection";
import { EntryCreate } from "../dto/EntryCreate";
import { EntryMessage } from "../dto/EntryMessage";
import { EntryUpdate } from "../dto/EntryUpdate";
import { EntryDelete } from "../dto/EntryDelete";
import { EntryPatch } from "../dto/EntryPatch";

@Controller()
export class AppController {
  @Get('/foo/:name/:type')
  @HttpCode(200)
  get(@Param('name') name: string, @Param('type') type: string, @Query('startIndex') startIndex: number, @Query('float') float: number, @Query('boolean') boolean: boolean, @Query('date') date: string, @Query('datetime') datetime: string, @Query('args') args: Entry): EntryCollection {
    // @TODO implement method
    return {};
  }

  @Post('/foo/:name/:type')
  @HttpCode(201)
  create(@Param('name') name: string, @Param('type') type: string, @Body() payload: EntryCreate): EntryMessage {
    // @TODO implement method
    return {};
  }

  @Put('/foo/:name/:type')
  @HttpCode(200)
  update(@Param('name') name: string, @Param('type') type: string, @Body() payload: Record<string, EntryUpdate>): Record<string, EntryMessage> {
    // @TODO implement method
    return {};
  }

  @Delete('/foo/:name/:type')
  @HttpCode(204)
  delete(@Param('name') name: string, @Param('type') type: string, @Body() payload: EntryDelete): EntryMessage {
    // @TODO implement method
    return {};
  }

  @Patch('/foo/:name/:type')
  @HttpCode(200)
  patch(@Param('name') name: string, @Param('type') type: string, @Body() payload: Array<EntryPatch>): Array<EntryMessage> {
    // @TODO implement method
    return {};
  }

}
