
// test_response automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type TestResponse struct {
    Args TestMapScalar `json:"args"`
    Headers TestMapScalar `json:"headers"`
    Json TestRequest `json:"json"`
    Method string `json:"method"`
}
