
// test_request automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type TestRequest struct {
    Int int `json:"int"`
    Float float64 `json:"float"`
    String string `json:"string"`
    Bool bool `json:"bool"`
    ArrayScalar []string `json:"arrayScalar"`
    ArrayObject []TestObject `json:"arrayObject"`
    MapScalar TestMapScalar `json:"mapScalar"`
    MapObject TestMapObject `json:"mapObject"`
    Object TestObject `json:"object"`
}
