/**
 * bar automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import { Controller, Get, Post, Put, Patch, Delete, HttpCode, Param, Query, Headers, Body } from '@nestjs/common'
import {EntryCollection} from "../../dto/EntryCollection";
import {EntryCreate} from "../../dto/EntryCreate";
import {EntryMessage} from "../../dto/EntryMessage";

@Controller()
export class BarController {
  @Get('/foo')
  @HttpCode(200)
  get(): EntryCollection {
    // @TODO implement method
  }

  @Post('/foo')
  @HttpCode(201)
  create(@Body() payload: EntryCreate): EntryMessage {
    // @TODO implement method
  }

}
