/**
 * baz automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import { Controller, Get, Post, Put, Patch, Delete, HttpCode, Param, Query, Headers, Body } from '@nestjs/common'
import { EntryCollection } from "../../dto/EntryCollection";
import { EntryCreate } from "../../dto/EntryCreate";
import { EntryMessage } from "../../dto/EntryMessage";

@Controller()
export class BazController {
  @Get('/bar/$year<[0-9]+>')
  @HttpCode(200)
  get(@Param('year') year: string): EntryCollection {
    // @TODO implement method
    return {};
  }

  @Post('/bar/$year<[0-9]+>')
  @HttpCode(201)
  create(@Body() payload: EntryCreate): EntryMessage {
    // @TODO implement method
    return {};
  }

}
