/**
 * EntryDelete automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface EntryDelete {
    id?: number
    userId?: number
    title?: string
    date?: string
}
