/**
 * ArrayEntryMessageException automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {KnownStatusCodeException} from "sdkgen-client"

import {EntryMessage} from "./EntryMessage";

export class ArrayEntryMessageException extends KnownStatusCodeException {

    public constructor(private payload: Array<EntryMessage>) {
        super('The server returned an error');
    }

    public getPayload(): Array<EntryMessage> {
        return this.payload;
    }

}
