/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ClientAbstract, CredentialsInterface, TokenStoreInterface} from "sdkgen-client"
import {HttpBearer} from "sdkgen-client"


export default class Client extends ClientAbstract {
    public constructor(baseUrl: string, token: string, tokenStore: TokenStoreInterface|null = null, scopes: Array<string>|null = []) {
        super(baseUrl, new HttpBearer(token), tokenStore, scopes);
    }


    /**
     * Returns a collection
     *
     * @returns {Promise<EntryCollection>}
     * @throws {ErrorException}
     */
    public async get(name: string, type: string, startIndex?: number, float?: number, boolean?: boolean, date?: string, datetime?: string): Promise<EntryCollection> {
        const url = this.parser.url('/foo/:name/:type', {
            name: name,
            type: type,
        });

        let params: AxiosRequestConfig = {
            url: url,
            method: 'GET',
            params: this.parser.query({
                startIndex: startIndex,
                float: float,
                boolean: boolean,
                date: date,
                datetime: datetime,
            }),
        };

        try {
            const response = await this.httpClient.request<EntryCollection>(params);
            return response.data;
        } catch (error) {
            if (axios.isAxiosError(error) && error.response) {
                switch (error.response.status) {
                    default:
                        throw new ErrorException('The server returned an unknown status code');
                }
            }

            throw new ErrorException('An unknown error occurred: ' + String(error));
        }
    }

    /**
     * @returns {Promise<EntryMessage>}
     * @throws {EntryMessageException}
     * @throws {EntryMessageException}
     * @throws {ErrorException}
     */
    public async create(name: string, type: string, payload: EntryCreate): Promise<EntryMessage> {
        const url = this.parser.url('/foo/:name/:type', {
            name: name,
            type: type,
        });

        let params: AxiosRequestConfig = {
            url: url,
            method: 'POST',
            params: this.parser.query({
            }),
            data: payload
        };

        try {
            const response = await this.httpClient.request<EntryMessage>(params);
            return response.data;
        } catch (error) {
            if (axios.isAxiosError(error) && error.response) {
                switch (error.response.status) {
                    case 400:
                        throw new EntryMessageException(error.response.data);
                    case 500:
                        throw new EntryMessageException(error.response.data);
                    default:
                        throw new ErrorException('The server returned an unknown status code');
                }
            }

            throw new ErrorException('An unknown error occurred: ' + String(error));
        }
    }

    /**
     * @returns {Promise<EntryMessage>}
     * @throws {ErrorException}
     */
    public async update(name: string, type: string, payload: EntryUpdate): Promise<EntryMessage> {
        const url = this.parser.url('/foo/:name/:type', {
            name: name,
            type: type,
        });

        let params: AxiosRequestConfig = {
            url: url,
            method: 'PUT',
            params: this.parser.query({
            }),
            data: payload
        };

        try {
            const response = await this.httpClient.request<EntryMessage>(params);
            return response.data;
        } catch (error) {
            if (axios.isAxiosError(error) && error.response) {
                switch (error.response.status) {
                    default:
                        throw new ErrorException('The server returned an unknown status code');
                }
            }

            throw new ErrorException('An unknown error occurred: ' + String(error));
        }
    }

    /**
     * @returns {Promise<EntryMessage>}
     * @throws {ErrorException}
     */
    public async delete(name: string, type: string, payload: EntryDelete): Promise<EntryMessage> {
        const url = this.parser.url('/foo/:name/:type', {
            name: name,
            type: type,
        });

        let params: AxiosRequestConfig = {
            url: url,
            method: 'DELETE',
            params: this.parser.query({
            }),
            data: payload
        };

        try {
            const response = await this.httpClient.request<EntryMessage>(params);
            return response.data;
        } catch (error) {
            if (axios.isAxiosError(error) && error.response) {
                switch (error.response.status) {
                    default:
                        throw new ErrorException('The server returned an unknown status code');
                }
            }

            throw new ErrorException('An unknown error occurred: ' + String(error));
        }
    }

    /**
     * @returns {Promise<EntryMessage>}
     * @throws {ErrorException}
     */
    public async patch(name: string, type: string, payload: EntryPatch): Promise<EntryMessage> {
        const url = this.parser.url('/foo/:name/:type', {
            name: name,
            type: type,
        });

        let params: AxiosRequestConfig = {
            url: url,
            method: 'PATCH',
            params: this.parser.query({
            }),
            data: payload
        };

        try {
            const response = await this.httpClient.request<EntryMessage>(params);
            return response.data;
        } catch (error) {
            if (axios.isAxiosError(error) && error.response) {
                switch (error.response.status) {
                    default:
                        throw new ErrorException('The server returned an unknown status code');
                }
            }

            throw new ErrorException('An unknown error occurred: ' + String(error));
        }
    }



}
