/**
 * EntryMessageException automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {KnownStatusCodeException} from "sdkgen-client"

import {EntryMessage} from "./EntryMessage";

export class EntryMessageException extends KnownStatusCodeException {

    public constructor(private payload: EntryMessage) {
        super('The server returned an error');
    }

    public getPayload(): EntryMessage {
        return this.payload;
    }

}
