/**
 * EntryMessageException automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {KnownErrorException} from "sdkgen-client"

import {EntryMessage} from "./EntryMessage";

export class EntryMessageException extends KnownErrorException {

    public constructor(private payload: EntryMessage) {
        super();
    }

    public getPayload(): EntryMessage {
        return this.payload;
    }

}
