/**
 * GetQuery automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface GetQuery {
    startIndex: number
    float?: number
    boolean?: boolean
    date?: string
    datetime?: string
}
