<?php
/**
 * baz automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace App\Controller;

use App\Model\EntryCollection;
use App\Model\EntryCreate;
use App\Model\EntryMessage;
use PSX\Api\Attribute\Body;
use PSX\Api\Attribute\Delete;
use PSX\Api\Attribute\Get;
use PSX\Api\Attribute\Param;
use PSX\Api\Attribute\Patch;
use PSX\Api\Attribute\Path;
use PSX\Api\Attribute\Post;
use PSX\Api\Attribute\Put;
use PSX\Api\Attribute\Query;
use PSX\Api\Attribute\StatusCode;
use PSX\Framework\Controller\ControllerAbstract;

class Baz extends ControllerAbstract
{
    #[Get]
    #[Path('/bar/$year<[0-9]+>')]
    #[StatusCode(200)]
    public function get(#[Param] string $year): EntryCollection
    {
        // @TODO implement method
    }

    #[Post]
    #[Path('/bar/$year<[0-9]+>')]
    #[StatusCode(201)]
    public function create(#[Body] EntryCreate $payload): EntryMessage
    {
        // @TODO implement method
    }

}
