<?php
/**
 * baz automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace App\Controller\Foo;

use App\Model;
use PSX\Api\Attribute\Body;
use PSX\Api\Attribute\Header;
use PSX\Api\Attribute\Param;
use PSX\Api\Attribute\Query;
use PSX\Api\Attribute\StatusCode;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Attribute\Route;

class Baz extends AbstractController
{
    #[Route('/bar/$year<[0-9]+>', methods: ['GET'])]
    #[StatusCode(200)]
    public function get(#[Param] string $year): Model\EntryCollection
    {
        // @TODO implement method
    }

    #[Route('/bar/$year<[0-9]+>', methods: ['POST'])]
    #[StatusCode(201)]
    public function create(#[Body] Model\EntryCreate $payload): Model\EntryMessage
    {
        // @TODO implement method
    }

}
