language: php
php:
  - 7.1
  - 7.2
  - 7.3
sudo: false
before_install:
  - if [ $TRAVIS_PHP_VERSION != '7.3' ]; then phpenv config-rm xdebug.ini; fi;
install:
  - composer install
script:
  - vendor/bin/phpunit
