language: php
php:
  - 7.2
  - 7.3
  - 7.4
sudo: false
before_install:
  - if [ $TRAVIS_PHP_VERSION == '7.2' ]; then phpenv config-rm xdebug.ini; fi;
install:
  - composer install
script:
  - vendor/bin/phpunit
