<?php
/**
 * app automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Controller;

use Model;
use PSX\Api\Attribute\Body;
use PSX\Api\Attribute\Header;
use PSX\Api\Attribute\Param;
use PSX\Api\Attribute\Query;
use PSX\Api\Attribute\StatusCode;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Attribute\Route;

class App extends AbstractController
{
    #[Route('/binary', methods: ['POST'])]
    #[StatusCode(200)]
    public function binary(#[Body] \Psr\Http\Message\StreamInterface $body): \Psr\Http\Message\StreamInterface
    {
        // @TODO implement method
    }

    #[Route('/form', methods: ['POST'])]
    #[StatusCode(200)]
    public function form(#[Body] \PSX\Data\Body\Form $body): \PSX\Data\Body\Form
    {
        // @TODO implement method
    }

    #[Route('/json', methods: ['POST'])]
    #[StatusCode(200)]
    public function json(#[Body] \PSX\Data\Body\Json $body): \PSX\Data\Body\Json
    {
        // @TODO implement method
    }

    #[Route('/multipart', methods: ['POST'])]
    #[StatusCode(200)]
    public function multipart(#[Body] \PSX\Data\Body\Multipart $body): \PSX\Data\Body\Multipart
    {
        // @TODO implement method
    }

    #[Route('/text', methods: ['POST'])]
    #[StatusCode(200)]
    public function text(#[Body] string $body): string
    {
        // @TODO implement method
    }

    #[Route('/xml', methods: ['POST'])]
    #[StatusCode(200)]
    public function xml(#[Body] string $body): string
    {
        // @TODO implement method
    }

}
