<?php
/**
 * MySchema automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Foo\Bar;


class MySchema implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    protected ?\External\Bar\MyType $foo = null;
    public function setFoo(?\External\Bar\MyType $foo): void
    {
        $this->foo = $foo;
    }
    public function getFoo(): ?\External\Bar\MyType
    {
        return $this->foo;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('foo', $this->foo);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
