<?php
/**
 * app automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace App\Controller;

use App\Model;
use PSX\Api\Attribute\Body;
use PSX\Api\Attribute\Delete;
use PSX\Api\Attribute\Get;
use PSX\Api\Attribute\Param;
use PSX\Api\Attribute\Patch;
use PSX\Api\Attribute\Path;
use PSX\Api\Attribute\Post;
use PSX\Api\Attribute\Put;
use PSX\Api\Attribute\Query;
use PSX\Api\Attribute\StatusCode;
use PSX\Framework\Controller\ControllerAbstract;

class App extends ControllerAbstract
{
    #[Post]
    #[Path('/binary')]
    #[StatusCode(200)]
    public function binary(#[Body] \Psr\Http\Message\StreamInterface $body): \Psr\Http\Message\StreamInterface
    {
        // @TODO implement method
    }

    #[Post]
    #[Path('/form')]
    #[StatusCode(200)]
    public function form(#[Body] \PSX\Data\Body\Form $body): \PSX\Data\Body\Form
    {
        // @TODO implement method
    }

    #[Post]
    #[Path('/json')]
    #[StatusCode(200)]
    public function json(#[Body] \PSX\Data\Body\Json $body): \PSX\Data\Body\Json
    {
        // @TODO implement method
    }

    #[Post]
    #[Path('/multipart')]
    #[StatusCode(200)]
    public function multipart(#[Body] \PSX\Data\Body\Multipart $body): \PSX\Data\Body\Multipart
    {
        // @TODO implement method
    }

    #[Post]
    #[Path('/text')]
    #[StatusCode(200)]
    public function text(#[Body] string $body): string
    {
        // @TODO implement method
    }

    #[Post]
    #[Path('/xml')]
    #[StatusCode(200)]
    public function xml(#[Body] \DOMDocument $body): \DOMDocument
    {
        // @TODO implement method
    }

}
