/**
 * BarGroup automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


import app.sdkgen.client.ResourceAbstract;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.http.client.HttpClient;

public class BarGroup extends ResourceAbstract {
    public BarGroup(String baseUrl, HttpClient httpClient, ObjectMapper objectMapper) {
        super(baseUrl, httpClient, objectMapper);
    }

    /**
     * Endpoint: /bar/:foo
     */
    public BarByFooResource getBarByFoo(String foo) {
        return new BarByFooResource(
            foo,
            this.baseUrl,
            this.httpClient
        );
    }

    /**
     * Endpoint: /bar/$year<[0-9]+>
     */
    public BarByYearResource getBarByYear(String year) {
        return new BarByYearResource(
            year,
            this.baseUrl,
            this.httpClient
        );
    }

}
