/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


import app.sdkgen.client.ClientAbstract;
import app.sdkgen.client.Credentials.*;
import app.sdkgen.client.CredentialsInterface;
import app.sdkgen.client.TokenStoreInterface;
import java.util.List;

public class Client extends ClientAbstract {
    public Client(String baseUrl, String token, TokenStoreInterface tokenStore, List<String> scopes) {
        super(baseUrl, new HttpBearer(token), tokenStore, scopes);
    }

    /**
     * Endpoint: /foo
     *
     * foo
     */
    public FooResource getFoo() {
        return new FooResource(
            this.baseUrl,
            this.newHttpClient(),
            this.objectMapper
        );
    }

    /**
     * Endpoint: /bar/:foo
     *
     * bar
     */
    public BarByFooResource getBarByFoo(String foo) {
        return new BarByFooResource(
            foo,
            this.baseUrl,
            this.newHttpClient(),
            this.objectMapper
        );
    }

    /**
     * Endpoint: /bar/$year<[0-9]+>
     *
     * bar
     */
    public BarByYearResource getBarByYear(String year) {
        return new BarByYearResource(
            year,
            this.baseUrl,
            this.newHttpClient(),
            this.objectMapper
        );
    }

}
