/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


import app.sdkgen.client.ClientAbstract;
import app.sdkgen.client.Credentials.*;
import app.sdkgen.client.Exception.ClientException;
import app.sdkgen.client.Exception.UnkownStatusCodeException;
import org.apache.http.HttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.client.utils.URIBuilder;
import org.apache.http.entity.ContentType;
import org.apache.http.entity.StringEntity;
import org.apache.http.util.EntityUtils;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

public class Client extends ClientAbstract {
    public function FooTag foo()
    {
        return new FooTag(
            $this->httpClient,
            $this->parser
        );
    }

    public function BarTag bar()
    {
        return new BarTag(
            $this->httpClient,
            $this->parser
        );
    }

    public function BazTag baz()
    {
        return new BazTag(
            $this->httpClient,
            $this->parser
        );
    }



    public static Client build(String baseUrl, String token): Client
    {
        return new Client(baseUrl, new HttpBearer(token));
    }
}
