/**
 * EntryCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class EntryCollection {
    private Entry[] entry;
    @JsonSetter("entry")
    public void setEntry(Entry[] entry) {
        this.entry = entry;
    }
    @JsonGetter("entry")
    public Entry[] getEntry() {
        return this.entry;
    }
}
