/**
 * FooGroup automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


import app.sdkgen.client.ResourceAbstract;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.http.client.HttpClient;

public class FooGroup extends ResourceAbstract {
    public FooGroup(String baseUrl, HttpClient httpClient, ObjectMapper objectMapper) {
        super(baseUrl, httpClient, objectMapper);
    }

    /**
     * Endpoint: /foo
     */
    public FooResource getFoo() {
        return new FooResource(
            this.baseUrl,
            this.httpClient
        );
    }

}
