/**
 * FooGroup automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


import app.sdkgen.client.ResourceAbstract;
import org.apache.http.client.HttpClient;

public class FooGroup extends ResourceAbstract {
    /**
     * Endpoint: /foo
     */
    public FooResource getFoo() {
        return new FooResource(
            this.baseUrl,
            this.token,
            this.httpClient
        );
    }

}
