/**
 * PathYear automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

public class PathYear {
    private String year;
    public void setYear(String year) {
        this.year = year;
    }
    public String getYear() {
        return this.year;
    }
}
