/**
 * PathFoo automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

public class PathFoo {
    private String foo;
    public void setFoo(String foo) {
        this.foo = foo;
    }
    public String getFoo() {
        return this.foo;
    }
}
