<?php
/**
 * bar automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace App\Controller;

use App\Model;
use PSX\Api\Attribute\Body;
use PSX\Api\Attribute\Delete;
use PSX\Api\Attribute\Get;
use PSX\Api\Attribute\Param;
use PSX\Api\Attribute\Patch;
use PSX\Api\Attribute\Path;
use PSX\Api\Attribute\Post;
use PSX\Api\Attribute\Put;
use PSX\Api\Attribute\Query;
use PSX\Api\Attribute\StatusCode;
use PSX\Framework\Controller\ControllerAbstract;

class Bar extends ControllerAbstract
{
    #[Get]
    #[Path('/bar/:foo')]
    #[StatusCode(200)]
    public function find(#[Param] string $foo): Model\EntryCollection
    {
        // @TODO implement method
    }

    #[Post]
    #[Path('/bar/:foo')]
    #[StatusCode(201)]
    public function put(#[Body] Model\EntryCreate $payload): Model\EntryMessage
    {
        // @TODO implement method
    }

}
