<?php
/**
 * bar automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace App\Controller;

use App\Model;
use PSX\Api\Attribute\Body;
use PSX\Api\Attribute\Header;
use PSX\Api\Attribute\Param;
use PSX\Api\Attribute\Query;
use PSX\Api\Attribute\StatusCode;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Attribute\Route;

class Bar extends AbstractController
{
    #[Route('/bar/:foo', methods: ['GET'])]
    #[StatusCode(200)]
    public function find(#[Param] string $foo): Model\EntryCollection
    {
        // @TODO implement method
    }

    #[Route('/bar/:foo', methods: ['POST'])]
    #[StatusCode(201)]
    public function put(#[Body] Model\EntryCreate $payload): Model\EntryMessage
    {
        // @TODO implement method
    }

}
