/**
 * EntryDelete automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

import java.time.LocalDateTime;
public class EntryDelete {
    private int id;
    private int userId;
    private String title;
    private LocalDateTime date;
    public void setId(int id) {
        this.id = id;
    }
    public int getId() {
        return this.id;
    }
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getUserId() {
        return this.userId;
    }
    public void setTitle(String title) {
        this.title = title;
    }
    public String getTitle() {
        return this.title;
    }
    public void setDate(LocalDateTime date) {
        this.date = date;
    }
    public LocalDateTime getDate() {
        return this.date;
    }
}
