/**
 * EntryCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

public class EntryCollection {
    private Entry[] entry;
    public void setEntry(Entry[] entry) {
        this.entry = entry;
    }
    public Entry[] getEntry() {
        return this.entry;
    }
}
