/**
 * EntryMessageException automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


import app.sdkgen.client.KnownErrorException;

public class EntryMessageException extends KnownErrorException {

    private EntryMessage payload;

    public EntryMessageException(EntryMessage payload) {
        super("The server returned an error");

        this.payload = payload;
    }

    public EntryMessage getPayload() {
        return this.payload;
    }

}
