/**
 * app automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import { Controller, Get, Post, Put, Patch, Delete, HttpCode, Param, Query, Headers, Body } from '@nestjs/common'

@Controller()
export class AppController {
  @Post('/binary')
  @HttpCode(200)
  binary(@Body() body: ArrayBuffer): ArrayBuffer {
    // @TODO implement method
    return {};
  }

  @Post('/form')
  @HttpCode(200)
  form(@Body() body: URLSearchParams): URLSearchParams {
    // @TODO implement method
    return {};
  }

  @Post('/json')
  @HttpCode(200)
  json(@Body() body: any): any {
    // @TODO implement method
    return {};
  }

  @Post('/multipart')
  @HttpCode(200)
  multipart(@Body() body: FormData): FormData {
    // @TODO implement method
    return {};
  }

  @Post('/text')
  @HttpCode(200)
  text(@Body() body: string): string {
    // @TODO implement method
    return {};
  }

  @Post('/xml')
  @HttpCode(200)
  xml(@Body() body: XMLDocument): XMLDocument {
    // @TODO implement method
    return {};
  }

}
