/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import axios, {AxiosRequestConfig} from "axios";
import {ClientAbstract, CredentialsInterface, TokenStoreInterface} from "sdkgen-client"
import {HttpBearer} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {ProductTag} from "./ProductTag";

export class Client extends ClientAbstract {
    public product(): ProductTag
    {
        return new ProductTag(
            this.httpClient,
            this.parser
        );
    }



    public static build(token: string): Client
    {
        return new Client('http://127.0.0.1:8081', new HttpBearer(token));
    }

    public static buildAnonymous(): Client
    {
        return new Client('http://127.0.0.1:8081', new Anonymous());
    }
}
