/**
 * TestRequest automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {TestObject} from "./TestObject";
import type {TestMapScalar} from "./TestMapScalar";
import type {TestMapObject} from "./TestMapObject";

export interface TestRequest {
    int?: number
    float?: number
    string?: string
    bool?: boolean
    dateString?: string
    dateTimeString?: string
    timeString?: string
    arrayScalar?: Array<string>
    arrayObject?: Array<TestObject>
    mapScalar?: TestMapScalar
    mapObject?: TestMapObject
    object?: TestObject
}

