/**
 * TestMapObject automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TestObject} from "./TestObject";

export interface TestMapObject extends Record<string, TestObject> {
}

