/**
 * TestRequest automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TestObject} from "./TestObject";
import {TestMapScalar} from "./TestMapScalar";
import {TestMapObject} from "./TestMapObject";
export interface TestRequest {
    int?: number
    float?: number
    string?: string
    bool?: boolean
    arrayScalar?: Array<string>
    arrayObject?: Array<TestObject>
    mapScalar?: TestMapScalar
    mapObject?: TestMapObject
    object?: TestObject
}
