/**
 * TestResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {TestMapScalar} from "./TestMapScalar";
import type {TestRequest} from "./TestRequest";

export interface TestResponse {
    args?: TestMapScalar
    data?: string
    files?: TestMapScalar
    form?: TestMapScalar
    headers?: TestMapScalar
    json?: TestRequest
    method?: string
}

