/**
 * TestResponseException automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {KnownStatusCodeException} from "sdkgen-client"

import {TestResponse} from "./TestResponse";

export class TestResponseException extends KnownStatusCodeException {

    public constructor(private payload: TestResponse) {
        super('The server returned an error');
    }

    public getPayload(): TestResponse {
        return this.payload;
    }

}
