/**
 * EntryOrMessage automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Entry} from "./Entry";
import {EntryMessage} from "./EntryMessage";
export type EntryOrMessage = Entry | EntryMessage;
