<?php
/**
 * XmlException automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Foo\Bar;

use Sdkgen\Client\Exception\KnownStatusCodeException;

class XmlException extends KnownStatusCodeException
{
    private \DOMDocument $payload;

    public function __construct(\DOMDocument $payload)
    {
        parent::__construct('The server returned an error');

        $this->payload = $payload;
    }

    /**
     * @return \DOMDocument
     */
    public function getPayload(): \DOMDocument
    {
        return $this->payload;
    }
}
