<?php
/**
 * BinaryException automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Sdkgen\Client\Tests\Generated;

use Sdkgen\Client\Exception\KnownStatusCodeException;

class BinaryException extends KnownStatusCodeException
{
    private \Psr\Http\Message\StreamInterface $payload;

    public function __construct(\Psr\Http\Message\StreamInterface $payload)
    {
        parent::__construct('The server returned an error');

        $this->payload = $payload;
    }

    /**
     * @return \Psr\Http\Message\StreamInterface
     */
    public function getPayload(): \Psr\Http\Message\StreamInterface
    {
        return $this->payload;
    }
}
