<?php
/**
 * JsonException automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Sdkgen\Client\Tests\Generated;

use Sdkgen\Client\Exception\KnownStatusCodeException;

class JsonException extends KnownStatusCodeException
{
    private \stdClass $payload;

    public function __construct(\stdClass $payload)
    {
        parent::__construct('The server returned an error');

        $this->payload = $payload;
    }

    /**
     * @return \stdClass
     */
    public function getPayload(): \stdClass
    {
        return $this->payload;
    }
}
