<?php
/**
 * TestRequest automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Sdkgen\Client\Tests\Generated;


class TestRequest implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    protected ?int $int = null;
    protected ?float $float = null;
    protected ?string $string = null;
    protected ?bool $bool = null;
    protected ?\PSX\DateTime\LocalDate $dateString = null;
    protected ?\PSX\DateTime\LocalDateTime $dateTimeString = null;
    protected ?\PSX\DateTime\LocalTime $timeString = null;
    /**
     * @var array<string>|null
     */
    protected ?array $arrayScalar = null;
    /**
     * @var array<TestObject>|null
     */
    protected ?array $arrayObject = null;
    protected ?TestMapScalar $mapScalar = null;
    protected ?TestMapObject $mapObject = null;
    protected ?TestObject $object = null;
    public function setInt(?int $int) : void
    {
        $this->int = $int;
    }
    public function getInt() : ?int
    {
        return $this->int;
    }
    public function setFloat(?float $float) : void
    {
        $this->float = $float;
    }
    public function getFloat() : ?float
    {
        return $this->float;
    }
    public function setString(?string $string) : void
    {
        $this->string = $string;
    }
    public function getString() : ?string
    {
        return $this->string;
    }
    public function setBool(?bool $bool) : void
    {
        $this->bool = $bool;
    }
    public function getBool() : ?bool
    {
        return $this->bool;
    }
    public function setDateString(?\PSX\DateTime\LocalDate $dateString) : void
    {
        $this->dateString = $dateString;
    }
    public function getDateString() : ?\PSX\DateTime\LocalDate
    {
        return $this->dateString;
    }
    public function setDateTimeString(?\PSX\DateTime\LocalDateTime $dateTimeString) : void
    {
        $this->dateTimeString = $dateTimeString;
    }
    public function getDateTimeString() : ?\PSX\DateTime\LocalDateTime
    {
        return $this->dateTimeString;
    }
    public function setTimeString(?\PSX\DateTime\LocalTime $timeString) : void
    {
        $this->timeString = $timeString;
    }
    public function getTimeString() : ?\PSX\DateTime\LocalTime
    {
        return $this->timeString;
    }
    /**
     * @param array<string>|null $arrayScalar
     */
    public function setArrayScalar(?array $arrayScalar) : void
    {
        $this->arrayScalar = $arrayScalar;
    }
    /**
     * @return array<string>|null
     */
    public function getArrayScalar() : ?array
    {
        return $this->arrayScalar;
    }
    /**
     * @param array<TestObject>|null $arrayObject
     */
    public function setArrayObject(?array $arrayObject) : void
    {
        $this->arrayObject = $arrayObject;
    }
    /**
     * @return array<TestObject>|null
     */
    public function getArrayObject() : ?array
    {
        return $this->arrayObject;
    }
    public function setMapScalar(?TestMapScalar $mapScalar) : void
    {
        $this->mapScalar = $mapScalar;
    }
    public function getMapScalar() : ?TestMapScalar
    {
        return $this->mapScalar;
    }
    public function setMapObject(?TestMapObject $mapObject) : void
    {
        $this->mapObject = $mapObject;
    }
    public function getMapObject() : ?TestMapObject
    {
        return $this->mapObject;
    }
    public function setObject(?TestObject $object) : void
    {
        $this->object = $object;
    }
    public function getObject() : ?TestObject
    {
        return $this->object;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('int', $this->int);
        $record->put('float', $this->float);
        $record->put('string', $this->string);
        $record->put('bool', $this->bool);
        $record->put('dateString', $this->dateString);
        $record->put('dateTimeString', $this->dateTimeString);
        $record->put('timeString', $this->timeString);
        $record->put('arrayScalar', $this->arrayScalar);
        $record->put('arrayObject', $this->arrayObject);
        $record->put('mapScalar', $this->mapScalar);
        $record->put('mapObject', $this->mapObject);
        $record->put('object', $this->object);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
