<?php
/**
 * TestRequest automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Sdkgen\Client\Tests\Generated;


class TestRequest implements \JsonSerializable
{
    protected ?int $int = null;
    protected ?float $float = null;
    protected ?string $string = null;
    protected ?bool $bool = null;
    /**
     * @var array<string>|null
     */
    protected ?array $arrayScalar = null;
    /**
     * @var array<TestObject>|null
     */
    protected ?array $arrayObject = null;
    protected ?TestMapScalar $mapScalar = null;
    protected ?TestMapObject $mapObject = null;
    protected ?TestObject $object = null;
    public function setInt(?int $int) : void
    {
        $this->int = $int;
    }
    public function getInt() : ?int
    {
        return $this->int;
    }
    public function setFloat(?float $float) : void
    {
        $this->float = $float;
    }
    public function getFloat() : ?float
    {
        return $this->float;
    }
    public function setString(?string $string) : void
    {
        $this->string = $string;
    }
    public function getString() : ?string
    {
        return $this->string;
    }
    public function setBool(?bool $bool) : void
    {
        $this->bool = $bool;
    }
    public function getBool() : ?bool
    {
        return $this->bool;
    }
    /**
     * @param array<string>|null $arrayScalar
     */
    public function setArrayScalar(?array $arrayScalar) : void
    {
        $this->arrayScalar = $arrayScalar;
    }
    public function getArrayScalar() : ?array
    {
        return $this->arrayScalar;
    }
    /**
     * @param array<TestObject>|null $arrayObject
     */
    public function setArrayObject(?array $arrayObject) : void
    {
        $this->arrayObject = $arrayObject;
    }
    public function getArrayObject() : ?array
    {
        return $this->arrayObject;
    }
    public function setMapScalar(?TestMapScalar $mapScalar) : void
    {
        $this->mapScalar = $mapScalar;
    }
    public function getMapScalar() : ?TestMapScalar
    {
        return $this->mapScalar;
    }
    public function setMapObject(?TestMapObject $mapObject) : void
    {
        $this->mapObject = $mapObject;
    }
    public function getMapObject() : ?TestMapObject
    {
        return $this->mapObject;
    }
    public function setObject(?TestObject $object) : void
    {
        $this->object = $object;
    }
    public function getObject() : ?TestObject
    {
        return $this->object;
    }
    public function jsonSerialize() : object
    {
        return (object) array_filter(array('int' => $this->int, 'float' => $this->float, 'string' => $this->string, 'bool' => $this->bool, 'arrayScalar' => $this->arrayScalar, 'arrayObject' => $this->arrayObject, 'mapScalar' => $this->mapScalar, 'mapObject' => $this->mapObject, 'object' => $this->object), static function ($value) : bool {
            return $value !== null;
        });
    }
}
