<?php
/**
 * TestMapScalar automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Sdkgen\Client\Tests\Generated;

/**
 * @extends \PSX\Record\Record<string>
 */
class TestMapScalar extends \PSX\Record\Record
{
}
