<?php
/**
 * TestResponseException automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Sdkgen\Client\Tests\Generated;

use Sdkgen\Client\Exception\KnownStatusCodeException;

class TestResponseException extends KnownStatusCodeException
{
    private TestResponse $payload;

    public function __construct(TestResponse $payload)
    {
        parent::__construct('The server returned an error');

        $this->payload = $payload;
    }

    /**
     * @return TestResponse
     */
    public function getPayload(): TestResponse
    {
        return $this->payload;
    }
}
