<?php
/**
 * TestResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Sdkgen\Client\Tests\Generated;


class TestResponse implements \JsonSerializable
{
    protected ?TestMapScalar $args = null;
    protected ?TestMapScalar $headers = null;
    protected ?TestRequest $json = null;
    protected ?string $method = null;
    public function setArgs(?TestMapScalar $args) : void
    {
        $this->args = $args;
    }
    public function getArgs() : ?TestMapScalar
    {
        return $this->args;
    }
    public function setHeaders(?TestMapScalar $headers) : void
    {
        $this->headers = $headers;
    }
    public function getHeaders() : ?TestMapScalar
    {
        return $this->headers;
    }
    public function setJson(?TestRequest $json) : void
    {
        $this->json = $json;
    }
    public function getJson() : ?TestRequest
    {
        return $this->json;
    }
    public function setMethod(?string $method) : void
    {
        $this->method = $method;
    }
    public function getMethod() : ?string
    {
        return $this->method;
    }
    public function jsonSerialize() : object
    {
        return (object) array_filter(array('args' => $this->args, 'headers' => $this->headers, 'json' => $this->json, 'method' => $this->method), static function ($value) : bool {
            return $value !== null;
        });
    }
}
