/**
 * ImportMyTypeException automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {KnownStatusCodeException} from "sdkgen-client"

import {MyType} from "./../foo/MyType";

export class ImportMyTypeException extends KnownStatusCodeException {

    public constructor(private payload: MyType) {
        super('The server returned an error');
    }

    public getPayload(): MyType {
        return this.payload;
    }

}
