/**
 * MySchema automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {MyType} from "./../foo/MyType";

export interface MySchema {
    foo?: MyType
}

