/**
 * MySchema automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {MyType} from "../foo";

export interface MySchema {
    foo?: MyType
}

