<?php
/**
 * BazTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Foo\Bar;

use Sdkgen\Client\TagAbstract;

class BazTag extends TagAbstract
{
    /**
     * @param EntryCreate $payload
     * @return EntryMessage
     * @throws \Sdkgen\Client\ErrorException
     */
    public function create(EntryCreate $payload): EntryMessage
    {
        $url = $this->parser->url('/bar/$year&lt;[0-9]+&gt;', [
        ]);

        $options = [
            'query' => $this->parser->query([
            ]),
            'json' => $payload
        ];

        try {
            $response = $this->httpClient->request('POST', $url, $options);
            $data     = (string) $response->getBody();

            return $this->parser->parse($data, EntryMessage::class);
        } catch (BadResponseException $e) {
            throw $this->parser->newException($e, [
            ]);
        } catch (\Throwable $e) {
            throw new ErrorException('An unknown error occurred: ' . $e->getMessage());
        }
    }


}
