<?php
/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Foo\Bar;

use Sdkgen\Client\ClientAbstract;
use Sdkgen\Client\Credentials;
use Sdkgen\Client\CredentialsInterface;
use Sdkgen\Client\TokenStoreInterface;

class Client extends ClientAbstract
{
    public function __construct(string $baseUrl, string $token, ?TokenStoreInterface $tokenStore = null, ?array $scopes = null)
    {
        parent::__construct($baseUrl, new Credentials\HttpBearer($token), $tokenStore, $scopes);
    }

    /**
     * Endpoint: /foo
     *
     * foo
     */
    public function getFoo(): FooResource
    {
        return new FooResource(
            $this->baseUrl,
            $this->newHttpClient(),
            $this->schemaManager
        );
    }

    /**
     * Endpoint: /bar/:foo
     *
     * bar
     */
    public function getBarByFoo(string $foo): BarByFooResource
    {
        return new BarByFooResource(
            $foo,
            $this->baseUrl,
            $this->newHttpClient(),
            $this->schemaManager
        );
    }

    /**
     * Endpoint: /bar/$year<[0-9]+>
     *
     * bar
     */
    public function getBarByYear(string $year): BarByYearResource
    {
        return new BarByYearResource(
            $year,
            $this->baseUrl,
            $this->newHttpClient(),
            $this->schemaManager
        );
    }

}
