<?php
/**
 * FooGroup automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Foo\Bar;

use Sdkgen\Client\ResourceAbstract;

class FooGroup extends ResourceAbstract
{
    /**
     * Endpoint: /foo
     */
    public function getFoo(): FooResource
    {
        return new FooResource(
            $this->baseUrl,
            $this->httpClient,
            $this->schemaManager
        );
    }

}
