<?php
/**
 * FooTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Foo\Bar;

use GuzzleHttp\Exception\BadResponseException;
use Sdkgen\Client\Exception\ClientException;
use Sdkgen\Client\Exception\UnknownStatusCodeException;
use Sdkgen\Client\TagAbstract;

class FooTag extends TagAbstract
{
    public function bar(): FooBarTag
    {
        return new FooBarTag(
            $this->httpClient,
            $this->parser
        );
    }

    public function baz(): FooBazTag
    {
        return new FooBazTag(
            $this->httpClient,
            $this->parser
        );
    }


}
