<?php
/**
 * PathYear automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Foo\Bar;


class PathYear implements \JsonSerializable
{
    protected ?string $year = null;
    public function setYear(?string $year) : void
    {
        $this->year = $year;
    }
    public function getYear() : ?string
    {
        return $this->year;
    }
    public function jsonSerialize() : object
    {
        return (object) array_filter(array('year' => $this->year), static function ($value) : bool {
            return $value !== null;
        });
    }
}
