/**
 * TestRequest automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package app.sdkgen.client.generated;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class TestRequest {
    private int _int;
    private double _float;
    private String string;
    private boolean bool;
    private String[] arrayScalar;
    private TestObject[] arrayObject;
    private TestMapScalar mapScalar;
    private TestMapObject mapObject;
    private TestObject object;
    @JsonSetter("int")
    public void setInt(int _int) {
        this._int = _int;
    }
    @JsonGetter("int")
    public int getInt() {
        return this._int;
    }
    @JsonSetter("float")
    public void setFloat(double _float) {
        this._float = _float;
    }
    @JsonGetter("float")
    public double getFloat() {
        return this._float;
    }
    @JsonSetter("string")
    public void setString(String string) {
        this.string = string;
    }
    @JsonGetter("string")
    public String getString() {
        return this.string;
    }
    @JsonSetter("bool")
    public void setBool(boolean bool) {
        this.bool = bool;
    }
    @JsonGetter("bool")
    public boolean getBool() {
        return this.bool;
    }
    @JsonSetter("arrayScalar")
    public void setArrayScalar(String[] arrayScalar) {
        this.arrayScalar = arrayScalar;
    }
    @JsonGetter("arrayScalar")
    public String[] getArrayScalar() {
        return this.arrayScalar;
    }
    @JsonSetter("arrayObject")
    public void setArrayObject(TestObject[] arrayObject) {
        this.arrayObject = arrayObject;
    }
    @JsonGetter("arrayObject")
    public TestObject[] getArrayObject() {
        return this.arrayObject;
    }
    @JsonSetter("mapScalar")
    public void setMapScalar(TestMapScalar mapScalar) {
        this.mapScalar = mapScalar;
    }
    @JsonGetter("mapScalar")
    public TestMapScalar getMapScalar() {
        return this.mapScalar;
    }
    @JsonSetter("mapObject")
    public void setMapObject(TestMapObject mapObject) {
        this.mapObject = mapObject;
    }
    @JsonGetter("mapObject")
    public TestMapObject getMapObject() {
        return this.mapObject;
    }
    @JsonSetter("object")
    public void setObject(TestObject object) {
        this.object = object;
    }
    @JsonGetter("object")
    public TestObject getObject() {
        return this.object;
    }
}
