/**
 * EntryMessage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

public class EntryMessage {
    private boolean success;
    private String message;
    public void setSuccess(boolean success) {
        this.success = success;
    }
    public boolean getSuccess() {
        return this.success;
    }
    public void setMessage(String message) {
        this.message = message;
    }
    public String getMessage() {
        return this.message;
    }
}
