/**
 * FormException automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {KnownStatusCodeException} from "sdkgen-client"


export class FormException extends KnownStatusCodeException {

    public constructor(private payload: URLSearchParams) {
        super('The server returned an error');
    }

    public getPayload(): URLSearchParams {
        return this.payload;
    }

}
