/**
 * MultipartException automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {KnownStatusCodeException} from "sdkgen-client"


export class MultipartException extends KnownStatusCodeException {

    public constructor(private payload: FormData) {
        super('The server returned an error');
    }

    public getPayload(): FormData {
        return this.payload;
    }

}
