
// Client automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    "github.com/apioo/sdkgen-go"
)

type Client struct {
    internal *sdkgen.Client
}

// Endpoint: /foo/:name/:type - lorem ipsum
func (client Client) GetFooByNameAndType(name string, _type string) *FooByNameAndTypeResource {
    return NewFooByNameAndTypeResource(name, _type, client.internal.GetResource())
}


func NewClient(baseUrl string, credentials sdkgen.CredentialsInterface, tokenStore sdkgen.TokenStoreInterface, scopes []string) *Client {

    return &Client {
        internal: sdkgen.NewClient(baseUrl, credentials, tokenStore, scopes),
    }
}
